# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish package to GitHub Packages
on: workflow_dispatch
#on:
#  release:
#    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      #- name: Validate Gradle wrapper
      #  uses: gradle/wrapper-validation-action@1fca1b1af7c3ed6cb9059346aaa89179c82abf11252837115e546c4da38e8b0c
      #- name: Git Publish package
      #  uses: gradle/gradle-build-action@v2
      #  with:
      #    arguments: publish
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #- name: Nexus Publish package
      #  uses: gradle/gradle-build-action@v2
      #  with:
      #    arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
      #    gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      #    gpg-passphrase: MAVEN_GPG_PASSPHRASE
      #  env:
      #    ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.ORG_GRADLE_PROJECT_sonatypeUsername }}
      #    ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.ORG_GRADLE_PROJECT_sonatypePassword }}
      #    MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}